package com.gp.learn.awardservice.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description="DTO reprenttion of AwardItem.")
public class AwardItemDTO {

	@ApiModelProperty(value="ID generated by the system.")
	private Long id;
	@ApiModelProperty(value="item number sent by C1. It is same number that McK sends to C1.",required=true)
	private Long economst;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getEconomst() {
		return economst;
	}
	public void setEconomst(Long economst) {
		this.economst = economst;
	}
	
	@Override
	public String toString() {
		return "AwardItemDTO [id=" + id + ", economst=" + economst + "]";
	}
	
}
