package com.gp.learn.awardservice.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "DTO representation of the Note entity.")
public class NoteDTO {

	@ApiModelProperty(value="primary key generated by the system.")
	private Long id;
	@ApiModelProperty(value="it captures user provided notes as well.",required = false)
	private String note;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	@Override
	public String toString() {
		return "NoteDTO [id=" + id + ", note=" + note + "]";
	}
	
	
}
